import './globals.css'
import { Montserrat } from 'next/font/google'


import NavBar from '@/components/nav_bar/navBar'


const font = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-black`  }>
      <NavBar/>
      {children}
      </body>
    </html>
  )
}
