import './globals.css'
import { Montserrat } from 'next/font/google'



import NavBar from '@/components/layout/nav_bar/navBar'
import Footer from '@/components/layout/footer/Footer'
const font = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable:false,
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-dark2`  }>
      <NavBar/>
    {children}
    <Footer/>
      </body>
    </html>
  )
}
