import './globals.css'
import { Montserrat } from 'next/font/google'


import NavBar from '@/components/layout/nav_bar/navBar'
import Footer from '@/components/layout/footer/Footer'
const font = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport:'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-dark2`  }>
      <NavBar/>
    {children}
    <Footer/>
      </body>
    </html>
  )
}
